# Generated by Django 3.1.2 on 2020-11-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0002_categoria_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
