# Generated by Django 3.1.2 on 2020-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0003_auto_20201108_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=60)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.TextField(max_length=60),
        ),
    ]
